export const booksData = [
    {
        name: "Managing Change Across Corporate Cultures: 3",
        slug: "history",
        category: "history",
        image: "images/e1.jpg",
        price: 100,
        rating: 4.2,
        numReviews: 6,
        countInStock: 18,
        description: "A Popular Book",
        aurhor:"xyz",
        savedAmount:250,
        discount:25

    },
    {
        name: "A Literary Salad : An Indispensable Companion For The Students And Teachers Of English Language Literature",
        slug: "literal",
        category: "old",
        image: "images/e2.jpg",
        price: 180,
        rating: 4.,
        numReviews: 9,
        countInStock: 10,
        description: "A Popular Book",
        aurhor:"xyz",
        savedAmount:250,
        discount:25
    },
    {
        name: "Yoga Books : Yoga for Children Step by Step",
        slug: "yoga",
        category: "yoga",
        image: "images/e3.jpg",
        price: 200,
        rating: 3.8,
        numReviews: 12,
        countInStock: 28,
        description: "A Best Book",
        aurhor:"xyz",
        savedAmount:250,
        discount:25
    },
    {
        name: "The Psychology of Money",
        slug: "Psychology",
        category: "Psychology",
        image: "images/e4.jpg",
        price: 170,
        rating: 4,
        numReviews: 22,
        countInStock: 10,
        description: "A Popular Book",
        aurhor:"xyz",
        savedAmount:250,
        discount:25
    },
    {
        name: "A Literary Salad : An Indispensable Companion For The Students And Teachers Of English Language Literature",
        slug: "literal",
        category: "old",
        image: "images/e2.jpg",
        price: 180,
        rating: 4.,
        numReviews: 9,
        countInStock: 10,
        description: "A Popular Book",
        aurhor:"xyz",
        savedAmount:250,
        discount:25
    },
    {
        name: "Managing Change Across Corporate Cultures: 3",
        slug: "history",
        category: "history",
        image: "images/e1.jpg",
        price: 100,
        rating: 4.2,
        numReviews: 6,
        countInStock: 18,
        description: "A Popular Book",
        aurhor:"xyz",
        savedAmount:250,
        discount:25
    },
    {
        name: "A Literary Salad : An Indispensable Companion For The Students And Teachers Of English Language Literature",
        slug: "literal",
        category: "old",
        image: "images/e2.jpg",
        price: 180,
        rating: 4.,
        numReviews: 9,
        countInStock: 10,
        description: "A Popular Book",
        aurhor:"xyz",
        savedAmount:250,
        discount:25
    },
    {
        name: "Yoga Books : Yoga for Children Step by Step",
        slug: "yoga",
        category: "yoga",
        image: "images/e3.jpg",
        price: 200,
        rating: 3.8,
        numReviews: 12,
        countInStock: 28,
        aurhor:"xyz",
        description: "A Best Book",
        aurhor:"xyz",
        savedAmount:250,
        discount:25
    },
    {
        name: "The Psychology of Money",
        slug: "Psychology",
        category: "Psychology",
        image: "images/e4.jpg",
        price: 170,
        rating: 4,
        numReviews: 22,
        countInStock: 10,
        description: "A Popular Book",
        aurhor:"xyz",
        savedAmount:250,
        discount:25
    },
    {
        name: "A Literary Salad : An Indispensable Companion For The Students And Teachers Of English Language Literature",
        slug: "literal",
        category: "old",
        image: "images/e2.jpg",
        price: 180,
        rating: 4.,
        numReviews: 9,
        countInStock: 10,
        description: "A Popular Book",
        aurhor:"xyz",
        savedAmount:250,
        discount:25
    },
]